# This file was generated by GoReleaser. DO NOT EDIT.
cask "ennote" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "0ea370c6032a7a5c42f79fb79c1a10af0ab5fd3e9f848a057c6d5c19845f561b"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "cab9962c0c1b987efd3db908d0e4ca472f89518cf49f3d853a160230b956723f"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a89d2edb4279d5a2613094c4bac91ae600b045e14d3220bc5aa2c0b5801147d"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "6ede171b06ac5d3efe7614cc08254b6801884169c5bf164f344ce39022140b95"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ennote"
  desc "The Identity-Driven Secret Manager CLI."
  homepage "https://ennote.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ennote"

  # No zap stanza required

end
