# This file was generated by GoReleaser. DO NOT EDIT.
cask "ennote" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "0b59052764dace4adc72d1aed69a1ec4756e3a9d247e13b42c39241b1ec87d47"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "de963868ca13d93cc04db81bd9386aa1e6289f0ffa82a41f8c5cd43646e93e44"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "65a924387600253615c4ce2de145741fde75461ec98aac3d57a438543d965bb7"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0afa5b2789bebfb1e6e235c863b2801380a3773c9069342fe6a10ea6c7dc77f6"
      url "https://github.com/ennote-io/ennote-cli/releases/download/v#{version}/ennote_#{version}_linux_arm64.tar.gz"
    end
  end

  name "ennote"
  desc "The Identity-Driven Secret Manager CLI."
  homepage "https://ennote.io"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ennote"

  # No zap stanza required

end
